### ISSUE TITLE
Installation on Windows inside electron

### ISSUE THREAD

**Issue by rgbkrk** [nteract/zmq-prebuilt#2]
Follow along with https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

```
npm install -g prebuild
git clone https://github.com/nteract/zmq-prebuilt
```

**Comment by rgbkrk** [comment]
Appears that the Python2 Nuget is broken while the Python3 Nuget is not. Any tips @carolynvs?

**Comment by rgbkrk** [comment]
Error I get out of the Python2 package on chocolatey:

```
Get-BinRoot is going to be deprecated by v1. Many packages no longer require it since the folders no longer have versions on them.
```

**Comment by rgbkrk** [comment]
It certainly installs though, putting it in the usual `C:\Python27` path on Windows. Seems like the `PATH` is just not being updated.

**Comment by rgbkrk** [comment]
Restarting seems to have helped, which I needed to do for Visual Studio anyway.

**Comment by carolynvs** [comment]
That message about `Get-BinRoot` is just a warning to whoever maintains the package.

With windows, PATH changes aren't picked up in the same session. You either need to start a new terminal (which restarting will do), or update the local PATH variable yourself, e.g. $env:PATH+=";C:\foo"

**Comment by rgbkrk** [comment]
@carolynvs Ok, sounds like if I throw a script together then I'll set the PATH as part of it. Thanks for your guidance, I have always been a Windows Padawan.

**Comment by carolynvs** [comment]
I have a dream... that one day MS will scrap NT and just redo their windowing system on top of *nix.

**Comment by minrk** [comment]
I set up a whole VM with chocolatey a couple of weeks ago and it got all borked. I trashed it and installed things manually and everything was better. I wouldn't recommend using Chocolatey to get Python or VC++ (as sad as that is).

**Comment by rgbkrk** [comment]
At the very least I've (re) found out I shouldn't be using Visual Studio 2015 even though node-gyp now supports it, because I still need VS 2013. In the past I've done the manual route and will reluctantly go back to it if I have to.

**Comment by rgbkrk** [comment]
https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

**Comment by rgbkrk** [comment]
We're going to need to build libzmq at the same commit hash we're using for \*nix builds, over in Visual Studio (and nuke the old DLLs).

**Comment by rgbkrk** [comment]
Jon was able to build and upload 32-bit binaries here. Yay!

**Comment by jdfreder** [comment]
I'll look into rebuilding for the proper commit tomorrow + 64bit

**Comment by stanleyxu2005** [comment]
Any updates? I'm looking everywhere to find an Electron compatible zmq.

**Comment by captainsafia** [comment]
@stanleyxu2005: We are working through support for different operating systems now. We've got OS X down and are currently cleaning up Linux support. Windows support will come later. We've got our own deadlines and so we anticipate it'll be one by the end of the month.

**Comment by rgbkrk** [comment]
@stanleyxu2005 As long as you use Electron < 1.2.8 you can use our prebuilds. We currently have Linux and OS X available, Windows is likely in the next couple weeks.

**Comment by stanleyxu2005** [comment]
@rgbkrk I have just downloaded Electron 1.2.7 (x64) and tried on Windows 7, but still the same error message. I don't know, whether I have missed something.
```
D:\ij\zmq-electron\node_modules\bindings\bindings.js:91 Uncaught Error: Could not locate the bindings file. Tried:
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\build\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\build\Debug\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\build\Release\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\out\Debug\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\Debug\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\out\Release\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\Release\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\build\default\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\compiled\6.1.0\win32\x64\zmq.node
```

**Comment by lgeiger** [comment]
> We currently have Linux and OS X available, Windows is likely in the next couple weeks.

The windows builds are working now but the packages are still broken. We're close.

**Comment by rgbkrk** [comment]
Do we need to bundle C++ DLLs?

https://github.com/zeromq/pyzmq/pull/870

**Comment by lgeiger** [comment]
Maybe relevant for bundling: https://github.com/mafintosh/prebuild/pull/122

**Comment by minrk** [comment]
From my understanding, you won't need them if:

- node ships them itself (Python ships CRT, but not C++)
- the bundled libzmq DLLs you link against have already statically linked those things (I don't know how to check this with confidence)

**Comment by rgbkrk** [comment]
At least in the case of Atom and Electron, the user may not actually have node. It's bundled as part of the electron install.

**Comment by lgeiger** [comment]
I have no idea about windows binaries but I noticed, during testing the windows fallback, there are more files in the `build/Release` folder compared to OS X:
```
zmq.node
zmq.lib
zmq.exp
zmq.map
zmq.pdb
```
On OS X only the `.node` files are generated. In both cases only the `.node` files are packaged and uploaded.
Do we need any of them?

**Comment by rgbkrk** [comment]
I have no idea, whatsoever.

**Comment by rgbkrk** [comment]
Thank you for digging into it.

**Comment by lgeiger** [comment]
We've released `v1.4.0` with working prebuilts for Windows 🎉 📦 .
I have tested them on Windows 10 (64-bit and 32-bit) with no problems.

**Comment by rgbkrk** [comment]
Yay!

**Comment by stanleyxu2005** [comment]
I still see the same error message as I mentioned with 1.4.0 on Windows 7

**Comment by rgbkrk** [comment]
What's your electron version?

**Comment by stanleyxu2005** [comment]
I'm using 1.2.7 (the one you explicitly mentioned)

**Comment by rgbkrk** [comment]
Can you try 1.1.3?

**Comment by rgbkrk** [comment]
1.1.3 of electron, 1.4.0 of zmq

**Comment by rgbkrk** [comment]
*zmq-prebuilt

**Comment by stanleyxu2005** [comment]
I tried electron-prebuilt 1.1.3 and zmq-prebuilt 1.4.0. The same error. What to do next.

**Comment by lgeiger** [comment]
Could you remove the `node_modules` folder in your project and try again?

**Comment by stanleyxu2005** [comment]
@leeiger I don't get your point. If I remove `node_modules`. electron and zmq-prebuilt will be removed. How to test my app then?

**Comment by lgeiger** [comment]
@stanleyxu2005 sorry I should have been more accurate. Remove the `node_modules` folder and run `npm install` inside your app directory to do a fresh install.

**Comment by stanleyxu2005** [comment]
Here are the commands I have ran:
```
npm install electron-prebuilt@1.1.3     # 64bit
npm install zmq-prebuilt
./node_modules/.bin/electron myapp
```
The `zmq.node` is located at `node_modules\zmq-prebuilt\build\Release\zmq.node`, but I see this error message.
```
D:\ij\zmq-electron\node_modules\bindings\bindings.js:91 Uncaught Error: Could not locate the bindings file. Tried:
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\build\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\build\Debug\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\build\Release\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\out\Debug\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\Debug\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\out\Release\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\Release\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\build\default\zmq.node
 → D:\ij\zmq-electron\node_modules\zmq-prebuilt\compiled\6.1.0\win32\x64\zmq.node
```

**Comment by rgbkrk** [comment]
I now have a Windows 10 64-bit machine and am using node 6.5.0 (for install), Electron 1.1.3. Pure node zmq worked (did a quick pub/sub), not so with Electron:

![zmq-electron](https://cloud.githubusercontent.com/assets/836375/18593064/5129fe96-7bff-11e6-85a8-5ab0bb4e2606.PNG)

**Comment by rgbkrk** [comment]
My next step was trying `electron-rebuild`:

```
npm install --save-dev electron-rebuild
.\node_modules\.bin\electron-rebuild.cmd
```

Which leads to me needing all the build tools, like Python2.

**Comment by rgbkrk** [comment]
On a side note, `npm install --global --production windows-build-tools` is super cool.

**Comment by rgbkrk** [comment]
Ooooh, that even sets up a local Python2 inside the build tools install. Whoa.

**Comment by stanleyxu2005** [comment]
In worst case, I'm thinking to fork a background process as proxy communicate with zmq.

**Comment by rgbkrk** [comment]
We'll keep working at it, hopefully you can build the rest of what you need for now.

**Comment by lgeiger** [comment]
This looks like it is trying to search for a DLL but zmq-prebuilt 1.4.0 statically links libzmq so there shouldn't be any DLLs. Maybe I'll find some time later this week to debug a bit more.

**Comment by rgbkrk** [comment]
It's so strange - the zmq-prebuilt worked on my fresh machine with _no problems_ in node. Only problems in Electron.

**Comment by stanleyxu2005** [comment]
@rgbkrk ZMQ only not working with Electron. If I'm using a node application, I can use ZMQ directly without using zmq-prebuilt.

**Comment by lgeiger** [comment]
@rgbkrk If we build against the correct electron headers with
```
node-gyp --target=1.4.0 --arch=x64 --dist-url=https://atom.io/download/atom-shell
```
instead of `prebuild --install` everything works fine.

With electron `v1.1.3` we can even do `node-gyp --target=1.1.3` or `prebuild --install --target=1.1.3`.

But that would mean we'll have to provide prebuilts for every electron version (even for the patch releases). That's a bit ridiculous considering there are almost 250 electron versions, but technically possible if we introduce this option to `prebuild`.

Sidenote: If we set `win_delay_hook: false` in the gyp file there is a different error: `Uncaught Error: Module did not self-register`. To fix the error google suggests enabling `win_delay_hook`. 😕 😄

**Comment by stanleyxu2005** [comment]
@lgeiger I don't understand well, why `zmq` works with Nodejs, but not works well with Electron. I was led to this project, because the contributor says they know the problem and how to fix it. If there is a script to build on Windows platform, that will be very helpful already. I can download required deps and build it on my own.

**Comment by rgbkrk** [comment]
> But that would mean we'll have to provide prebuilts for every electron version (even for the patch releases). That's a bit ridiculous considering there are almost 250 electron versions, but technically possible if we introduce this option to prebuild.

I think we only have to match electron versions per ABI. Also, I think it's a-ok to build a ridiculous number of prebuilds (or at least only the releases from the past year).

**Comment by stanleyxu2005** [comment]
Hi team, could you provide the link of Electron, that exactly works with `zmq-prebuilt`. I want to test, whether I can use that for my project. I highly doubt that the root cause is at linking with `node.dll`. To build Electron is a bit difficult in China mainland, as the most dependencies are not accessible without a good proxy.

**Comment by rgbkrk** [comment]
It does not work yet, we're still working on it. You'd have to build from scratch yourself with the electron headers, as @lgeiger did above. If you are able to solve it, we definitely want to know as well.

**Comment by lgeiger** [comment]
@stanleyxu2005  Take a look at https://github.com/nteract/nteract/pull/903. We got it working on windows as long as you have the required build tools installed.

If you want to work with the latest version of electron and don't mind building from source. Check out [zmq-static](https://github.com/nteract/zmq-static).

**Comment by lgeiger** [comment]
`zmq-prebuilt` v1.5.0 can be rebuilt to work with all electron releases as long as you have the required build tools installed.

**Comment by rgbkrk** [comment]
@captainsafia want to adapt `@captainsafia/jmp-prebuilt` to rely on the latest version of `zmq-prebuilt` - `v1.5.0`?

**Comment by lgeiger** [comment]
`v1.5.0` is now available through `npm`.

**Comment by stanleyxu2005** [comment]
@lgeiger What are those *required build tools* for Electron release?

**Comment by stanleyxu2005** [comment]
@lgeiger Thanks for the heads up. I really appreciated the research work. However I still fail to load zmq-prebuilt on a Electron application. It is the same error as I posted before.

What I have done is that:
* Windows 7 x64 SP1
* ZeroMQ 4.0.4 x64
* The Visual CPP Build Tool (4GB) with Default option (as you described in readme)
* Python 2.11.7 (Anaconda2 edition) x64
* Electron 1.4.3 x64
* Node 6.6.0 x64 (with the latest node-gyp)

I successfully run the build (with 84 warnings, no error) using `npm install` against the latest code from your master branch. And then I copy the whole directory `zmq-prebuilt` into `node_modules` and then launch my application. And then see the error message.

![log](https://cloud.githubusercontent.com/assets/5162687/19181736/a18c6484-8ca1-11e6-9590-c650f6df514a.PNG)

**Comment by lgeiger** [comment]
@stanleyxu2005 You're almost there. The warnings seem to be normal.

ZeroMQ 4.0.4 x64 doesn't need to be installed, but it doesn't hurt either (We bundle it inside `zmq-prebuilt`.

Now you have to rebuild `zmq-prebuilt` for electron because it uses a different version of node and v8 which isn't ABI compatible. To do this I would usually recommend [`electron-rebuild`](https://github.com/electron/electron-rebuild) but I experienced some issues on windows.

You can do the rebuilding manually by running `npm rebuild zmq-prebuilt --runtime=electron --target=1.4.3 --disturl=https://atom.io/download/atom-shell --build-from-source` inside your electron app directory where `zmq-prebuilt` is installed. You can take a look at https://github.com/nteract/nteract/pull/903 for more info.

**Comment by stanleyxu2005** [comment]
Now I fully understand your approach. I will give a try shortly. As rebuilding electronjs is not a good experience, it'd be great, if your team have some public `electron & zmq` prebuilt bundle that we can just use.

**Comment by lgeiger** [comment]
@stanleyxu2005 The command won't rebuild electron. It will only rebuild `zmq-prebuilt` with electron headers instead of the node headers.

**Comment by lgeiger** [comment]
We just shipped `v2.0.0`. With your setup you should be able to use it as a normal dependency and add the rebuild command to the `postinstall` script in the `package.json`.

**Comment by stanleyxu2005** [comment]
@lgeiger Finally I can confirm that ZMQ is now engaged with Electron. A ton of thanks for making this happen!

**Comment by lgeiger** [comment]
@stanleyxu2005 That's excellent news! 🎉 

You're the first testing it for real on windows.

**Comment by stanleyxu2005** [comment]
Just one note: Although I have only visual studio build tool (2015) and set msvs_version to 2015. But it always says .net framework 2.0 is not found. I added "--msvs_version=2015" and it works.

**Comment by lgeiger** [comment]
Setting the environment variable `GYP_MSVS_VERSION` to `2015` should work as well. At least that's what the `windows-build-tools` are doing.

**Comment by stanleyxu2005** [comment]
This might be the reason. Actually I think a better way is using appveyor to build and publish to a repo. This will avoid a lot of trouble. ;-)

**Comment by rgbkrk** [comment]
We're using appveyor now, there's not a standard for prebuilt binaries for native packages targeting electron yet.

The other option is building electron from source and including zmq, but that would be a ridiculous path (considering all the tools that rely on `electron`, I don't want to go this route).

**Comment by stanleyxu2005** [comment]
Got it. I also notice a potential packaging issue: The `node_module` directory after installing `zmq-prebuilt` will be 36MB on my machine. This will be a bit too large for a slow connection for first time downloading. I tried to shrink the package to less than 2MB by remaining only `bindings` and `nan` and `zmq-prebuilt/build` (sure including all readme and license files). I'm thinking whether there should something in package.json to run a postinstall script to clean up irrelevant stuffs.
